# Directories arguments
#data_root: "D:/A3D/ego_accident/dataset"
#checkpoint_dir: "./checkpoints/ap_model"

#best_fol_model: './checkpoints/fol_wo_ego_vanilla_avg/fol_epoch_079_loss_0.0060.pt'
#best_fol_model: './checkpoints/fol_vanilla_wo_ego/HEVI/seg_16_pred_10_absolute_concat/fol_epoch_100_loss_0.0057.pt'
#best_ap_model: './checkpoints/train_on_DoTA/concatenation/AdaLEA/epoch_036.pt' #36

best_fol_model: './checkpoints/bbox_delta/fol_epoch_121_loss_0.0063.pt'
#best_fol_model: './checkpoints/Final/delta_reduction_AdaLEA2/bbox_delta/fol_epoch_121_loss_0.0063.pt'
#best_ap_model: './checkpoints/Final/flow_mrcnn_delta_AdaLEA_cross_1/epoch_055.pt' #36
#best_ap_model: './checkpoints/Final/flow_mrcnn_delta_AdaLEA_cross_3/epoch_031.pt' #36
best_ap_model: './checkpoints/Final/flow_mrcnn_delta_AdaLEA_2/epoch_087.pt' #36
#best_ap_model: './checkpoints/Final/dataset_reduction_delta/epoch_049.pt' #36

future_context_size: 128

# dataset arguments
seed_max: 5
segment_len: 16

# training parameters
nb_fol_epoch: 10 #1000
nb_ego_pred_epoch: 200
lr: 0.0001

lambda_fol: 1
lambda_ego: 1
device: 'cuda'

# fol model parameters
pred_timesteps: 10
input_embed_size: 512
flow_enc_size: 512
box_enc_size: 512
with_ego: False #True

enc_hidden_size: 512 # no use
enc_concat_type: "cat"
predictor_input_size: 512
dec_hidden_size: 512
pred_dim: 4


# ego_pred model parameters
ego_embed_size: 128
ego_enc_size: 128
ego_dec_size: 128
ego_pred_input_size: 128
ego_dim: 3

# dataloader parameters
batch_size: 1
shuffle: True
num_workers: 0

# image parameters
H: 720
W: 1280
channels: 3

flow_roi_size: [5,5,2]

# Anomaly detection parameters
max_age: 10
