# Directories arguments
data_root: "./ap_train_dataset/DoTA_based/dataset_reduction/"

best_fol_model: './checkpoints/fol_vanilla_wo_ego/HEVI/seg_16_pred_10_absolute_concat/fol_epoch_100_loss_0.0057.pt'

# dataset arguments
seed_max: 5
segment_len: 16

# training parameters
nb_fol_epoch: 100
nb_ego_pred_epoch: 200
lr: 0.0001

lambda_fol: 1
lambda_ego: 1
device: 'cuda'

# fol model parameters
pred_timesteps: 10 #5
input_embed_size: 512
flow_enc_size: 512
box_enc_size: 512
with_ego: False

enc_hidden_size: 512 # no use
enc_concat_type: "cat"
predictor_input_size: 512
dec_hidden_size: 512
pred_dim: 4


# ego_pred model parameters
ego_embed_size: 128
ego_enc_size: 128
ego_dec_size: 128
ego_pred_input_size: 128
ego_dim: 3

# dataloader parameters
batch_size: 1
shuffle: False
num_workers: 0

# image parameters
H: 720
W: 1280
channels: 3

flow_roi_size: [5,5,2]

# Anomaly detection parameters
max_age: 10
